# TCL File Generated by Component Editor 15.1
# Fri Apr 01 10:32:01 CST 2016
# DO NOT MODIFY


# 
# census "ins_census" v1.4
# Macrobull 2016.04.01.10:32:01
# Census functions
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module census
# 
set_module_property DESCRIPTION "Census functions"
set_module_property NAME census
set_module_property VERSION 1.4
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP MyIns
set_module_property AUTHOR Macrobull
set_module_property DISPLAY_NAME ins_census
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL census
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ins_census.v VERILOG PATH ins_census.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point census
# 
add_interface census nios_custom_instruction end
set_interface_property census clockCycle 2
set_interface_property census operands 1
set_interface_property census ENABLED true
set_interface_property census EXPORT_OF ""
set_interface_property census PORT_NAME_MAP ""
set_interface_property census CMSIS_SVD_VARIABLES ""
set_interface_property census SVD_ADDRESS_GROUP ""

add_interface_port census oRes result Output 32
add_interface_port census iA dataa Input 32
add_interface_port census iOp n Input 4
add_interface_port census iReset reset Input 1
add_interface_port census iClk clk Input 1
add_interface_port census iClk_en clk_en Input 1

