# TCL File Generated by Component Editor 15.1
# Thu Mar 31 14:12:40 CST 2016
# DO NOT MODIFY


# 
# cesus "ins_cesus" v1.3
# Macrobull 2016.03.31.14:12:40
# Cesus functions
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module cesus
# 
set_module_property DESCRIPTION "Cesus functions"
set_module_property NAME cesus
set_module_property VERSION 1.3
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP MyIns
set_module_property AUTHOR Macrobull
set_module_property DISPLAY_NAME ins_cesus
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL cesus
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ins_cesus.v VERILOG PATH ins_cesus.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point cesus
# 
add_interface cesus nios_custom_instruction end
set_interface_property cesus clockCycle 2
set_interface_property cesus operands 2
set_interface_property cesus ENABLED true
set_interface_property cesus EXPORT_OF ""
set_interface_property cesus PORT_NAME_MAP ""
set_interface_property cesus CMSIS_SVD_VARIABLES ""
set_interface_property cesus SVD_ADDRESS_GROUP ""

add_interface_port cesus iA dataa Input 32
add_interface_port cesus iB datab Input 32
add_interface_port cesus iClk clk Input 1
add_interface_port cesus iReset reset Input 1
add_interface_port cesus iOp n Input 4
add_interface_port cesus oRes result Output 32
add_interface_port cesus iClk_en clk_en Input 1

