# TCL File Generated by Component Editor 15.1
# Thu Mar 31 03:30:44 CST 2016
# DO NOT MODIFY


# 
# cesus "ins_cesus" v1.0
# Macrobull 2016.03.31.03:30:44
# Cesus functions
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module cesus
# 
set_module_property DESCRIPTION "Cesus functions"
set_module_property NAME cesus
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP MyIns
set_module_property AUTHOR Macrobull
set_module_property DISPLAY_NAME ins_cesus
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL cesus
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ins_cesus.v VERILOG PATH ins_cesus.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point ins_cesus
# 
add_interface ins_cesus nios_custom_instruction end
set_interface_property ins_cesus clockCycle 0
set_interface_property ins_cesus operands 2
set_interface_property ins_cesus ENABLED true
set_interface_property ins_cesus EXPORT_OF ""
set_interface_property ins_cesus PORT_NAME_MAP ""
set_interface_property ins_cesus CMSIS_SVD_VARIABLES ""
set_interface_property ins_cesus SVD_ADDRESS_GROUP ""

add_interface_port ins_cesus oRes result Output 32
add_interface_port ins_cesus oDone done Output 1
add_interface_port ins_cesus iA dataa Input 32
add_interface_port ins_cesus iB datab Input 32
add_interface_port ins_cesus iClk clk Input 1
add_interface_port ins_cesus iClk_en clk_en Input 1
add_interface_port ins_cesus iStart start Input 1
add_interface_port ins_cesus iReset reset Input 1
add_interface_port ins_cesus iOp n Input 4

