# TCL File Generated by Component Editor 15.1
# Fri Apr 01 19:03:46 CST 2016
# DO NOT MODIFY


# 
# t0 "ins_t0" v1.0
# Macrobull 2016.04.01.19:03:46
# test with DMA
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module t0
# 
set_module_property DESCRIPTION "test with DMA"
set_module_property NAME t0
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP MyIns
set_module_property AUTHOR Macrobull
set_module_property DISPLAY_NAME ins_t0
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL t0
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file ins_test.v VERILOG PATH ins_test.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_reset reset Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_address address Input 8
add_interface_port s0 avs_s0_read read Input 1
add_interface_port s0 avs_s0_readdata readdata Output 32
add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_writedata writedata Input 32
add_interface_port s0 avs_s0_waitrequest waitrequest Output 1
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point tcs0
# 
add_interface tcs0 tristate_conduit end
set_interface_property tcs0 associatedClock clock
set_interface_property tcs0 ENABLED true
set_interface_property tcs0 EXPORT_OF ""
set_interface_property tcs0 PORT_NAME_MAP ""
set_interface_property tcs0 CMSIS_SVD_VARIABLES ""
set_interface_property tcs0 SVD_ADDRESS_GROUP ""

add_interface_port tcs0 tcs_tcs0_grant grant Output 1
add_interface_port tcs0 tcs_tcs0_request request Input 1


# 
# connection point tcm0
# 
add_interface tcm0 tristate_conduit start
set_interface_property tcm0 associatedClock clock
set_interface_property tcm0 ENABLED true
set_interface_property tcm0 EXPORT_OF ""
set_interface_property tcm0 PORT_NAME_MAP ""
set_interface_property tcm0 CMSIS_SVD_VARIABLES ""
set_interface_property tcm0 SVD_ADDRESS_GROUP ""

add_interface_port tcm0 tcm_tcm0_grant grant Input 1
add_interface_port tcm0 tcm_tcm0_request request Output 1


# 
# connection point cis0
# 
add_interface cis0 nios_custom_instruction end
set_interface_property cis0 clockCycle 0
set_interface_property cis0 operands 2
set_interface_property cis0 ENABLED true
set_interface_property cis0 EXPORT_OF ""
set_interface_property cis0 PORT_NAME_MAP ""
set_interface_property cis0 CMSIS_SVD_VARIABLES ""
set_interface_property cis0 SVD_ADDRESS_GROUP ""

add_interface_port cis0 ncs_cis0_dataa dataa Input 32
add_interface_port cis0 ncs_cis0_datab datab Input 32
add_interface_port cis0 ncs_cis0_result result Output 32
add_interface_port cis0 ncs_cis0_clk clk Input 1
add_interface_port cis0 ncs_cis0_clk_en clk_en Input 1
add_interface_port cis0 ncs_cis0_start start Input 1
add_interface_port cis0 ncs_cis0_reset reset Input 1
add_interface_port cis0 ncs_cis0_done done Output 1


# 
# connection point avm_m0
# 
add_interface avm_m0 avalon start
set_interface_property avm_m0 addressUnits SYMBOLS
set_interface_property avm_m0 associatedClock clock
set_interface_property avm_m0 associatedReset reset
set_interface_property avm_m0 bitsPerSymbol 8
set_interface_property avm_m0 burstOnBurstBoundariesOnly false
set_interface_property avm_m0 burstcountUnits WORDS
set_interface_property avm_m0 doStreamReads false
set_interface_property avm_m0 doStreamWrites false
set_interface_property avm_m0 holdTime 0
set_interface_property avm_m0 linewrapBursts false
set_interface_property avm_m0 maximumPendingReadTransactions 0
set_interface_property avm_m0 maximumPendingWriteTransactions 0
set_interface_property avm_m0 readLatency 0
set_interface_property avm_m0 readWaitTime 1
set_interface_property avm_m0 setupTime 0
set_interface_property avm_m0 timingUnits Cycles
set_interface_property avm_m0 writeWaitTime 0
set_interface_property avm_m0 ENABLED true
set_interface_property avm_m0 EXPORT_OF ""
set_interface_property avm_m0 PORT_NAME_MAP ""
set_interface_property avm_m0 CMSIS_SVD_VARIABLES ""
set_interface_property avm_m0 SVD_ADDRESS_GROUP ""

add_interface_port avm_m0 avm_m0_address address Output 32
add_interface_port avm_m0 avm_m0_read read Output 1
add_interface_port avm_m0 avm_m0_waitrequest waitrequest Input 1
add_interface_port avm_m0 avm_m0_readdata readdata Input 32
add_interface_port avm_m0 avm_m0_write write Output 1
add_interface_port avm_m0 avm_m0_writedata writedata Output 32

