# TCL File Generated by Component Editor 15.1
# Thu Mar 31 21:04:42 CST 2016
# DO NOT MODIFY


# 
# test "ins_test" v1.0
# Macrobull 2016.03.31.21:04:42
# test extended ZERO cycle instruction
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module test
# 
set_module_property DESCRIPTION "test extended ZERO cycle instruction"
set_module_property NAME test
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP MyIns
set_module_property AUTHOR Macrobull
set_module_property DISPLAY_NAME ins_test
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL test
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ins_test.v VERILOG PATH ins_test.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point test
# 
add_interface test nios_custom_instruction end
set_interface_property test clockCycle 2
set_interface_property test operands 2
set_interface_property test ENABLED true
set_interface_property test EXPORT_OF ""
set_interface_property test PORT_NAME_MAP ""
set_interface_property test CMSIS_SVD_VARIABLES ""
set_interface_property test SVD_ADDRESS_GROUP ""

add_interface_port test oRes result Output 32
add_interface_port test iA dataa Input 32
add_interface_port test iB datab Input 32
add_interface_port test iOp n Input 4
add_interface_port test iClk clk Input 1
add_interface_port test iReset reset Input 1
add_interface_port test iClk_en clk_en Input 1

